version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    entrypoint: ["flask", "run"]
    networks:
      - default
    depends_on:
      - db
  db:
    image: "postgres:latest"
    networks:
      - default
  jenkins:
    image: jenkinsci/blueocean
    user: root
    ports:
      - "8080:8080"
      - "8443:8443"
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      ##### Mac OS X and Linux ONLY #####
      - //var/run/docker.sock:/var/run/docker.sock
    # - /var/run/docker.sock:/var/run/docker.sock
    # command: OPS
    # Testing
    # Linter
    # Build
    # Push to Dockerhub
    # Deploy from Dockerhub

networks:
  default:
    driver: bridge